name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_SECRET_KEY: ${{ secrets.CC_PRACTICE_SEC_QN_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
